version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      [80:80] #80:80 is working
    volumes:
      [./src:/var/www/html/]

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      [8080:8080] #8080:8080 is working

  web:
    build: .
    stdin_open: true
    tty: true
    ports: 
      [4202:4202]
    volumes: 
      - "/app/node_modules"
      - ".:/app"


